version: '3.3'
services:
    alist:
        restart: always
        volumes:
            - ${PWD}/alist:/opt/alist/data
        ports:
            - 5244:5244
        environment:
            - PUID=0
            - PGID=0
            - UMASK=022
        container_name: alist
        image: xhofe/alist:latest
    Aria2-Pro:
        container_name: aria2-pro
        image: p3terx/aria2-pro
        environment:
            - PUID=65534
            - PGID=65534
            - UMASK_SET=022
            - RPC_SECRET=jPopnL
            - RPC_PORT=6800
            - LISTEN_PORT=6888
            - DISK_CACHE=64M
            - IPV6_MODE=false
            - UPDATE_TRACKERS=true
            - TZ=Asia/Shanghai
        volumes:
            - ${PWD}/aria2-config:/config
            - ${PWD}/alist/temp/downloads:/downloads
            - ${PWD}/alist/temp/aria2:/opt/alist/data/temp/aria2
# If you use host network mode, then no port mapping is required.
# This is the easiest way to use IPv6 networks.
#        network_mode: host
        network_mode: bridge
        ports:
            - 6800:6800
            - 6888:6888
            - 6888:6888/udp
        restart: unless-stopped
# Since Aria2 will continue to generate logs, limit the log size to 1M to prevent your hard disk from running out of space.
        logging:
            driver: json-file
            options:
                max-size: 1m
